import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toast";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Produqtedge - Onboarding Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans text-textColor antialiased`}
      >
        <NextTopLoader color="#F68E1E" showSpinner={false} />
          {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
